name: fhir_to_senzing

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  fhir: ^0.4.7
  fhir_bulk: ^0.4.4
  freezed_annotation: ^0.14.2
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner: ^2.0.6
  freezed: ^0.14.2
  json_serializable: ^4.1.4